version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: hori_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hori
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: hori_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/hori
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: hori_frontend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
